from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import Any

from analytics_workflow.decision_tree_figure import decision_tree_imbalance_note, decision_tree_performance_note

from .chart_renderer import has_structured_chart_data
from .deck_spec import ContentBlock, DeckSpec, SlideSpec, VisualSpec
from .templates import ANALYSIS_TEMPLATE_SEQUENCE, REQUIRED_SLIDE_ROLES, TEMPLATE_REGISTRY, template_for_legacy_layout
from .text_refiner import compact_whitespace, first_nonempty, refine_bullets, refine_headline, shorten, soften_unsupported_impact_claim
from .validators import repair_deck_spec, validate_deck_spec


def build_deck_spec(workflow_state: dict[str, Any]) -> DeckSpec:
    ppt_mcp_spec = workflow_state.get("ppt_mcp_deck_spec")
    if isinstance(ppt_mcp_spec, dict) and ppt_mcp_spec.get("slides"):
        deck = DeckSpec.from_any(ppt_mcp_spec)
        deck.metadata = {**deck.metadata, "design_source": "ppt_mcp"}
        _confine_external_deck_visuals(deck, workflow_state)
        return _finalize_deck(deck, workflow_state, legacy_warnings=[], polish=False)

    outputs = workflow_state.get("agent_outputs", {}) or {}
    plan = outputs.get("presentation_architect", {}) or {}
    dataset_context = _dataset_context(workflow_state)
    deck_title = first_nonempty(
        plan.get("deck_title"),
        plan.get("presentation_title"),
        outputs.get("decision_maker", {}).get("title"),
        "Analytics Executive Brief",
    )
    subtitle = first_nonempty(
        plan.get("subtitle"),
        plan.get("presentation_subtitle"),
        dataset_context.get("description"),
        "Generated by the Multi-Agent Analytics System",
    )
    subtitle = _clean_context_description(subtitle, dataset_context)
    deck = DeckSpec(
        deck_title=shorten(deck_title, 90),
        subtitle=shorten(subtitle, 120),
        audience=compact_whitespace(plan.get("audience")) or "executive",
        theme=compact_whitespace(plan.get("theme")) or "consulting_minimal",
        metadata=_metadata(workflow_state),
        dataset_context=dataset_context,
        slides=[],
    )

    legacy_by_role, legacy_warnings = _legacy_slides_by_role(plan.get("slides", []) or [])
    visuals = _analysis_artifact_queue(workflow_state)
    findings = _analysis_findings(workflow_state)

    deck.slides = [
        _title_slide(deck, workflow_state, legacy_by_role),
        _data_understanding_slide(workflow_state, legacy_by_role),
        _market_context_slide(workflow_state, legacy_by_role),
        *_analysis_slides(workflow_state, visuals, findings, legacy_by_role),
        _findings_slide(workflow_state, legacy_by_role),
        _business_translation_slide(workflow_state, legacy_by_role),
        _recommendations_slide(workflow_state, legacy_by_role),
        _limitations_slide(workflow_state, legacy_by_role),
        _summary_slide(workflow_state, legacy_by_role),
    ]
    return _finalize_deck(deck, workflow_state, legacy_warnings=legacy_warnings)


def _finalize_deck(
    deck: DeckSpec,
    workflow_state: dict[str, Any],
    *,
    legacy_warnings: list[dict[str, Any]],
    polish: bool = True,
) -> DeckSpec:
    deck.renumber()
    _attach_evidence_metadata(deck, workflow_state)
    if polish:
        _polish_deck_slides(deck)
    preexisting_warnings = list(workflow_state.get("slide_validation_warnings", []) or [])
    pre_repair_warnings = [
        {**warning, "phase": "pre_repair"}
        for warning in validate_deck_spec(deck)
        if isinstance(warning, dict)
    ]
    repair_deck_spec(deck)
    if polish:
        _polish_deck_slides(deck)
    post_repair_warnings = [
        {**warning, "phase": "post_repair"}
        for warning in validate_deck_spec(deck)
        if isinstance(warning, dict)
    ]
    workflow_state["deck_spec"] = deck.to_dict()
    workflow_state["slide_validation_warnings"] = (
        preexisting_warnings + legacy_warnings + pre_repair_warnings + post_repair_warnings
    )
    workflow_state["slide_unresolved_warnings"] = post_repair_warnings
    return deck


def _attach_evidence_metadata(deck: DeckSpec, workflow_state: dict[str, Any]) -> None:
    bundle = workflow_state.get("evidence_bundle", {}) or {}
    records = {
        compact_whitespace(item.get("evidence_id")): item
        for item in bundle.get("evidence", []) or []
        if isinstance(item, dict) and compact_whitespace(item.get("evidence_id"))
    }
    dataset_source_ids = [
        compact_whitespace(item.get("source_id"))
        for item in bundle.get("datasets", []) or []
        if isinstance(item, dict) and compact_whitespace(item.get("source_id"))
    ]
    recommendations = (
        workflow_state.get("agent_outputs", {}).get("decision_maker", {}).get("recommendations", []) or []
    )
    recommendation_ids = [
        compact_whitespace(evidence_id)
        for item in recommendations
        if isinstance(item, dict)
        for evidence_id in item.get("evidence_ids", []) or []
        if compact_whitespace(evidence_id)
    ]
    high_stakes = bool(bundle.get("high_stakes"))
    for slide in deck.slides:
        evidence_ids: list[str] = []
        if slide.visual is not None:
            visual_id = compact_whitespace(slide.visual.artifact_id or slide.visual.chart_spec_id)
            if visual_id and visual_id in records:
                record = records[visual_id]
                evidence_ids.append(visual_id)
                slide.visual.evidence_ids = [visual_id]
                slide.visual.source_ids = list(record.get("source_ids", []) or dataset_source_ids)
                slide.visual.sample_size = record.get("sample_size") if isinstance(record.get("sample_size"), int) else None
                slide.visual.denominator = compact_whitespace(record.get("denominator"))
                slide.visual.method = compact_whitespace(record.get("method"))
                slide.visual.confidence = compact_whitespace(record.get("confidence"))
                slide.visual.caveat = shorten(record.get("caveat", ""), 180)
        if slide.slide_role == "data_understanding":
            slide.source_ids = dataset_source_ids
        elif slide.slide_role == "recommendations":
            evidence_ids.extend(recommendation_ids)
        elif slide.slide_role in {"limitations", "summary", "ending"}:
            evidence_ids.extend(list(records)[:4])
        slide.evidence_ids = list(dict.fromkeys(evidence_ids))[:5]
        slide.source_ids = list(
            dict.fromkeys(
                slide.source_ids
                + [source for evidence_id in slide.evidence_ids for source in records.get(evidence_id, {}).get("source_ids", [])]
            )
        )[:5]
        slide.decision_status = "human_review_required" if high_stakes and slide.slide_role in {"recommendations", "summary", "ending"} else "validation_required" if slide.slide_role == "recommendations" else ""
        caveats = [records[item].get("caveat", "") for item in slide.evidence_ids if item in records and records[item].get("caveat")]
        slide.caveat = shorten(first_nonempty(*caveats), 180)
        note_parts = []
        if slide.evidence_ids:
            note_parts.append("Evidence: " + ", ".join(slide.evidence_ids))
        if slide.source_ids:
            note_parts.append("Sources: " + ", ".join(slide.source_ids))
        detail_bits: list[str] = []
        for evidence_id in slide.evidence_ids[:3]:
            record = records.get(evidence_id, {})
            if record.get("method"):
                detail_bits.append(f"{evidence_id} method={record.get('method')}")
            if record.get("sample_size"):
                detail_bits.append(f"n={record.get('sample_size')}")
            if record.get("denominator"):
                detail_bits.append(f"denominator={record.get('denominator')}")
        if detail_bits:
            note_parts.append("; ".join(detail_bits))
        if slide.caveat:
            note_parts.append("Caveat: " + slide.caveat)
        slide.speaker_note = shorten(" | ".join(note_parts), 220)


def _confine_external_deck_visuals(deck: DeckSpec, workflow_state: dict[str, Any]) -> None:
    allowed_paths = {
        str(Path(str(path)).resolve())
        for path in (
            list(workflow_state.get("saved_figures", []) or [])
            + list(workflow_state.get("analysis_results", {}).get("figures_generated", []) or [])
        )
        if path
    }
    for slide in deck.slides:
        visual = slide.visual
        if not visual or not visual.image_path:
            continue
        try:
            resolved = str(Path(visual.image_path).resolve())
        except OSError:
            resolved = ""
        if resolved not in allowed_paths:
            slide.visual = None
        else:
            visual.image_path = resolved


def _metadata(workflow_state: dict[str, Any]) -> dict[str, Any]:
    manifest = workflow_state.get("run_manifest", {}) or {}
    bundle = workflow_state.get("evidence_bundle", {}) or {}
    return {
        "generated_by": "Multi-Agent Analytics System",
        "generated_on": datetime.now().strftime("%B %d, %Y"),
        "run_id": manifest.get("run_id", ""),
        "evidence_bundle_hash": bundle.get("bundle_hash", ""),
        "evidence_sources": {
            "datasets": list(bundle.get("datasets", []) or []),
            "external_sources": list(bundle.get("external_sources", []) or []),
            "evidence_ids": [
                compact_whitespace(item.get("evidence_id"))
                for item in bundle.get("evidence", []) or []
                if isinstance(item, dict) and compact_whitespace(item.get("evidence_id"))
            ],
            "quality_status": (workflow_state.get("quality_receipt", {}) or {}).get("status", ""),
        },
        "recommendation_execution": [
            {
                key: item.get(key, "")
                for key in ("rank", "action", "owner", "trigger", "validation_metric", "stop_condition", "timeline", "evidence_ids")
            }
            for item in workflow_state.get("agent_outputs", {}).get("decision_maker", {}).get("recommendations", []) or []
            if isinstance(item, dict)
        ][:3],
    }


def _dataset_context(workflow_state: dict[str, Any]) -> dict[str, Any]:
    outputs = workflow_state.get("agent_outputs", {}) or {}
    data = outputs.get("data_understander", {}) or {}
    datasets = data.get("datasets", {}) if isinstance(data, dict) else {}
    name = ""
    rows = None
    columns = None
    key_fields: list[str] = []
    quality_notes: list[str] = []
    if isinstance(datasets, dict) and datasets:
        name, first = next(iter(datasets.items()))
        if isinstance(first, dict):
            shape = first.get("shape") or []
            if len(shape) >= 2:
                rows, columns = shape[0], shape[1]
            key_fields = [str(item) for item in first.get("columns", [])[:8]]
            quality_notes = refine_bullets(
                [first.get("quality_summary", "")] + first.get("cleaning_priorities", []) + first.get("type_notes", []),
                max_items=4,
            )
    if not key_fields:
        for df in (workflow_state.get("csv_data", {}) or {}).values():
            key_fields = [str(column) for column in getattr(df, "columns", [])[:8]]
            if key_fields:
                if rows is None:
                    rows = len(df)
                if columns is None:
                    columns = len(getattr(df, "columns", []))
                break
    manifest_datasets = workflow_state.get("run_manifest", {}).get("datasets", []) or []
    if not name and manifest_datasets:
        first_manifest = manifest_datasets[0]
        if isinstance(first_manifest, dict):
            name = compact_whitespace(first_manifest.get("name"))
            rows = first_manifest.get("rows", rows)
    return {
        "name": name,
        "description": _clean_context_description(
            first_nonempty(
                workflow_state.get("data_description"),
                workflow_state.get("user_data_description"),
                workflow_state.get("workflow_objective", {}).get("raw_description") if isinstance(workflow_state.get("workflow_objective"), dict) else "",
                data.get("executive_summary") if isinstance(data, dict) else "",
            ),
            {"name": name, "key_fields": key_fields},
        ),
        "rows": rows,
        "columns": columns,
        "target": compact_whitespace(workflow_state.get("decision_tree_target_column")) or _infer_target(key_fields),
        "key_fields": key_fields,
        "data_quality_notes": quality_notes,
    }


def _infer_target(fields: list[str]) -> str:
    for field in fields:
        lowered = field.lower()
        if any(token in lowered for token in ("target", "outcome", "churn", "risk", "default", "label")):
            return field
    return ""


def _clean_context_description(value: Any, context: dict[str, Any]) -> str:
    text = compact_whitespace(value)
    name = compact_whitespace(context.get("name"))
    fields = [compact_whitespace(field) for field in context.get("key_fields", []) if compact_whitespace(field)]
    if not text or _looks_like_generation_instruction(text):
        return _dataset_short_description(name, fields)
    if " produce " in f" {text.lower()} " or " use only evidence " in text.lower():
        return _dataset_short_description(name, fields)
    return text


def _dataset_short_description(name: str, fields: list[str]) -> str:
    field_text = ", ".join(fields[:6])
    if _looks_like_stock_name(name) or _looks_like_stock_fields(fields):
        return f"{name or 'Stock price history'} with price, volume, return, and date fields for time-series evidence."
    if name and field_text:
        return f"{name} with key fields: {field_text}."
    if name:
        return name
    if field_text:
        return f"Dataset with key fields: {field_text}."
    return "Dataset prepared for executive evidence review."


def _looks_like_generation_instruction(text: str) -> bool:
    lower = compact_whitespace(text).lower()
    return any(
        phrase in lower
        for phrase in (
            "produce dataset-specific",
            "produce a business-readable",
            "executive slides",
            "do not train",
            "use only evidence visible",
            "generate report",
        )
    )


def _looks_like_stock_name(name: str) -> bool:
    lower = compact_whitespace(name).lower()
    return bool(re.search(r"\b(stock|share price|ohlc|stc)\b", lower))


def _looks_like_stock_fields(fields: list[str]) -> bool:
    lowered = {field.lower().strip() for field in fields}
    return bool({"date", "price"} & lowered) and any(
        token in lowered for token in ("vol.", "volume", "change %", "open", "high", "low", "close")
    )


def _legacy_slides_by_role(raw_slides: list[Any]) -> tuple[dict[str, list[SlideSpec]], list[dict[str, Any]]]:
    grouped: dict[str, list[SlideSpec]] = {}
    warnings: list[dict[str, Any]] = []
    for index, raw in enumerate(raw_slides, start=1):
        if not isinstance(raw, dict):
            continue
        raw_template = compact_whitespace(raw.get("template"))
        raw_layout = compact_whitespace(raw.get("layout_type"))
        if raw_template and raw_template not in TEMPLATE_REGISTRY:
            warnings.append({"scope": "legacy_slide", "slide": index, "issue": "unsupported_template", "template": raw_template})
        if raw_layout and raw_layout not in {"cover", "executive_summary", "dataset_overview", "kpi_cards", "chart_focus", "chart_with_takeaways", "two_column_insight", "insight_cards", "recommendation_matrix", "risk_limitations", "closing"}:
            warnings.append({"scope": "legacy_slide", "slide": index, "issue": "invalid_layout_type", "layout_type": raw_layout})
        visual_path = compact_whitespace(raw.get("visual_path") or raw.get("visual_element"))
        if visual_path and not Path(visual_path).exists():
            warnings.append({"scope": "legacy_slide", "slide": index, "issue": "missing_visual_reference", "visual_path": visual_path})
        details = raw.get("details", []) or []
        if isinstance(details, list) and len(details) > 5:
            warnings.append({"scope": "legacy_slide", "slide": index, "issue": "too_many_bullets"})
        slide = SlideSpec.from_legacy(raw, index)
        if "template" not in raw and raw.get("layout_type"):
            slide.template = template_for_legacy_layout(compact_whitespace(raw.get("layout_type")))
        elif "template" not in raw and not raw.get("layout_type"):
            slide.template = ""
        role = compact_whitespace(raw.get("slide_role")) or _infer_role(raw, index)
        slide.slide_role = role
        grouped.setdefault(role, []).append(slide)
    return grouped, warnings


def _infer_role(raw: dict[str, Any], index: int) -> str:
    text = f"{raw.get('title', '')} {raw.get('headline', '')} {raw.get('layout_type', '')}".lower()
    if index == 1 and "cover" in text:
        return "title"
    if "dataset" in text or "data understanding" in text or "objective" in text:
        return "data_understanding"
    if "market" in text or "context" in text:
        return "market_context"
    if "recommend" in text or "decision" in text:
        return "recommendations"
    if "limit" in text or "risk" in text:
        return "limitations"
    if "finding" in text or "evidence" in text:
        return "findings"
    if "business" in text or "translation" in text:
        return "business_translation"
    if "closing" in text or "summary" in text:
        return "summary"
    return "analysis"


def _pop_legacy(grouped: dict[str, list[SlideSpec]], role: str) -> SlideSpec | None:
    slides = grouped.get(role, [])
    return slides.pop(0) if slides else None


def _title_slide(deck: DeckSpec, workflow_state: dict[str, Any], legacy: dict[str, list[SlideSpec]]) -> SlideSpec:
    existing = _pop_legacy(legacy, "title")
    context = _clean_context_description(deck.dataset_context.get("description") or deck.subtitle, deck.dataset_context)
    return _merge_slide(
        existing,
        SlideSpec(
            1,
            "title",
            "title_cover",
            deck.deck_title,
            "Generated by the Multi-Agent Analytics System",
            subtitle=shorten(context, 120),
            content_blocks=[],
        ),
    )


def _data_understanding_slide(workflow_state: dict[str, Any], legacy: dict[str, list[SlideSpec]]) -> SlideSpec:
    existing = _pop_legacy(legacy, "data_understanding")
    context = _dataset_context(workflow_state)
    metrics = []
    if context.get("rows") is not None:
        metrics.append({"label": "Rows", "value": str(context.get("rows"))})
    if context.get("columns") is not None:
        metrics.append({"label": "Columns", "value": str(context.get("columns"))})
    if context.get("target"):
        metrics.append({"label": "Target", "value": str(context.get("target"))})
    quality_status = compact_whitespace((workflow_state.get("quality_receipt", {}) or {}).get("status"))
    if quality_status:
        metrics.append({"label": "Quality", "value": quality_status.replace("_", " ").title()})
    for metric in _summary_metrics(workflow_state):
        if len(metrics) >= 4:
            break
        if not any(item.get("label") == metric.get("label") for item in metrics):
            metrics.append(metric)
    key_fields = context.get("key_fields", []) or []
    fields = ", ".join(key_fields[:8])
    bullets = refine_bullets(
        [
            context.get("description"),
            f"Key fields include {fields}" if fields else "",
            f"Target field is {context.get('target')}" if context.get("target") else "",
            "Use lending fairness and governance checks before changing underwriting actions." if _is_lending_context(workflow_state) else "",
        ],
        max_items=5,
        max_chars=150,
    )
    slide = SlideSpec(
        2,
        "data_understanding",
        "data_understanding_overview",
        _data_understanding_headline(workflow_state),
        "Use the data profile to understand what evidence is reliable and where caution is needed.",
        content_blocks=[ContentBlock(type="bullets", items=bullets)],
        metrics=metrics,
    )
    return _merge_slide(existing, slide)


def _data_understanding_headline(workflow_state: dict[str, Any]) -> str:
    if workflow_state.get("decision_tree_target_column"):
        return "The dataset supports a structured evidence review"
    return "The dataset is ready to support a focused decision review"


def _market_context_slide(workflow_state: dict[str, Any], legacy: dict[str, list[SlideSpec]]) -> SlideSpec:
    existing = _pop_legacy(legacy, "market_context")
    market = workflow_state.get("agent_outputs", {}).get("market_researcher", {}) or {}
    if _market_context_conflicts_with_dataset(market, workflow_state):
        headline = "Market context requires ticker disambiguation"
        bullets = refine_bullets(
            [
                "External sources appear to mix STC ticker contexts; treat them as unverified until source mapping is confirmed.",
                "Use the CSV price, volume, return, and date evidence as the reliable basis for this run.",
                "Decision implication: validate any market-outlook claim before it changes portfolio action.",
            ],
            max_items=3,
            max_chars=150,
        )
    elif _has_cited_market_context(market):
        if str(market.get("market_evidence_level", "")).lower() == "search_snippet":
            headline = "External context is directional and requires source-page review"
        else:
            headline = "Domain context uses cited market evidence"
        bullets = _cited_market_bullets(market)
    elif market.get("sources_cited"):
        headline = "External sources were captured, but their claims require review"
        bullets = refine_bullets(
            [
                f"[{source.get('index', index)}] {source.get('title', 'External source')} - search-snippet context only."
                for index, source in enumerate(market.get("sources_cited", [])[:3], start=1)
                if isinstance(source, dict)
            ],
            max_items=3,
            max_chars=150,
        )
    else:
        headline = "Domain context uses dataset-grounded assumptions"
        bullets = refine_bullets(
            [
                "No cited external market source/date was captured for this run.",
                "Treat this slide as internal decision context, not external market research.",
                _domain_context_validation_bullet(workflow_state),
            ],
            max_items=3,
            max_chars=150,
        )
    if not bullets:
        headline = "Domain context should be interpreted from the dataset and objective"
        bullets = ["No external market research was captured for this run.", "Use the dataset profile and stated objective as the decision context."]
    slide = SlideSpec(
        3,
        "market_context",
        "market_context_bullets",
        headline,
        "This context frames why the evidence is useful for decision-makers.",
        content_blocks=[ContentBlock(type="bullets", items=bullets)],
    )
    return _merge_slide(existing, slide)


def _domain_context_validation_bullet(workflow_state: dict[str, Any]) -> str:
    if _is_lending_context(workflow_state):
        return "Implication: validate policy changes against current credit conditions and governance constraints."
    if workflow_state.get("decision_tree_target_column"):
        return "Implication: validate screening or outreach decisions before operational use."
    return "Implication: validate recommended actions against current operating conditions before rollout."


def _market_context_conflicts_with_dataset(market: dict[str, Any], workflow_state: dict[str, Any]) -> bool:
    context = _dataset_context(workflow_state)
    context_text = f"{context.get('name', '')} {context.get('description', '')}".lower()
    if not _looks_like_stock_name(context_text):
        return False
    market_text = compact_whitespace(market).lower()
    return "stewart information" in market_text and any(token in context_text for token in ("stc", "saudi", "telecom"))


def _has_cited_market_context(market: dict[str, Any]) -> bool:
    sources = market.get("sources_cited", []) if isinstance(market, dict) else []
    findings = market.get("market_findings", []) if isinstance(market, dict) else []
    return bool(sources and findings)


def _cited_market_bullets(market: dict[str, Any]) -> list[str]:
    sources: dict[int, dict[str, Any]] = {}
    for fallback, source in enumerate(market.get("sources_cited", []) or [], start=1):
        if not isinstance(source, dict):
            continue
        try:
            index = int(source.get("index", fallback))
        except (TypeError, ValueError):
            index = fallback
        sources[index] = source
    bullets: list[str] = []
    for fallback, finding in enumerate(market.get("market_findings", []) or [], start=1):
        if not isinstance(finding, dict):
            continue
        try:
            source_index = int(finding.get("source_index", fallback))
        except (TypeError, ValueError):
            source_index = fallback
        source = sources.get(source_index, {})
        source_label = compact_whitespace(source.get("title") or f"Source {source_index}")
        source_date = compact_whitespace(source.get("published_date") or source.get("date") or source.get("accessed") or "")
        claim = compact_whitespace(finding.get("claim"))
        implication = compact_whitespace(finding.get("implication") or finding.get("relevance") or source.get("relevance"))
        date_text = f", {source_date}" if source_date else ""
        bullets.append(f"{claim} [{source_index}: {source_label}{date_text}]. Implication: {implication or 'validate portfolio actions against this context.'}")
    return refine_bullets(bullets, max_items=4, max_chars=180)


def _analysis_slides(
    workflow_state: dict[str, Any],
    visuals: list[VisualSpec],
    findings: list[str],
    legacy: dict[str, list[SlideSpec]],
) -> list[SlideSpec]:
    slides: list[SlideSpec] = []
    for offset in range(4):
        existing = _pop_legacy(legacy, "analysis")
        visual = visuals[offset] if offset < len(visuals) else (existing.visual if existing else None)
        finding = (
            (visual.finding if visual and visual.finding else "")
            or (visual.takeaway if visual and visual.takeaway else "")
            or (findings[offset] if offset < len(findings) else "")
        )
        if visual and visual.chart_type == "decision_tree":
            finding = _decision_tree_caveat(visual) or finding
        template = _template_for_visual(visual, offset)
        if not visual and template in {
            "chart_left_insight_right",
            "chart_right_insight_left",
            "full_width_chart_takeaway",
            "metric_strip_plus_chart",
            "small_multiples_with_takeaway",
            "single_bar_chart_with_insight",
            "horizontal_bar_ranking",
            "metric_cards_with_chart",
            "comparison_chart_with_interpretation",
            "distribution_with_callout",
        }:
            template = "segment_profile_cards" if offset == 3 else "comparison_matrix"
        headline = _visual_aligned_headline(visual, finding, offset, existing.headline if existing else "")
        bullets = refine_bullets(
            [finding, visual.takeaway if visual else "", visual.title if visual else ""]
            if visual
            else (existing.bullets if existing else [finding]),
            max_items=3,
        )
        slide = SlideSpec(
            4 + offset,
            "analysis",
            _choose_template(existing, visual, template),
            headline,
            shorten(finding if visual else (existing.main_message if existing else finding), 170),
            content_blocks=[ContentBlock(type="bullets", items=bullets)],
            visual=visual,
            metrics=_summary_metrics(workflow_state) if template in {"metric_strip_plus_chart", "metric_cards_with_chart"} else [],
        )
        merged = _merge_slide(existing, slide)
        if visual:
            merged.headline = headline
            merged.main_message = shorten(finding or visual.takeaway or visual.title, 170)
            merged.content_blocks = [ContentBlock(type="bullets", items=bullets)]
        slides.append(merged)
    return slides


def _visual_aligned_headline(
    visual: VisualSpec | None,
    finding: str,
    offset: int,
    existing_headline: str = "",
) -> str:
    if visual:
        if visual.chart_type == "decision_tree":
            return refine_headline("", _decision_tree_visual_headline(visual))
        ranked_headline = _ranked_value_headline(visual)
        if ranked_headline:
            return refine_headline("", ranked_headline)
        evidence_text = first_nonempty(visual.finding, visual.takeaway, visual.title, finding)
        if visual.type == "code_figure" and evidence_text:
            evidence_text = _remove_unverified_ratio_claim(evidence_text)
            if _headline_overlap_count(existing_headline, evidence_text) >= 3:
                return refine_headline(existing_headline, evidence_text)
            return refine_headline("", evidence_text)
        if _headlines_overlap(existing_headline, evidence_text):
            return refine_headline(existing_headline, evidence_text)
        return refine_headline(
            "",
            first_nonempty(
                visual.finding,
                visual.takeaway,
                visual.title,
                finding,
                f"Finding {offset + 1} points to a practical decision signal",
            ),
        )
    return refine_headline("", finding or f"Finding {offset + 1} points to a practical decision signal")


def _ranked_value_headline(visual: VisualSpec) -> str:
    if visual.chart_type not in {"bar", "column", "horizontal_bar", "ranking", "grouped_bar"}:
        return ""
    rows = visual.data if isinstance(visual.data, list) else []
    if not rows:
        return ""
    category_key = visual.x or visual.group_by or _first_row_key(rows, ("category", "label", "segment", "group", "name"))
    value_key = visual.y or _first_numeric_row_key(rows)
    if not category_key or not value_key:
        return ""
    points: list[tuple[str, float]] = []
    for row in rows:
        if not isinstance(row, dict):
            continue
        label = compact_whitespace(row.get(category_key))
        try:
            value = float(row.get(value_key))
        except (TypeError, ValueError):
            continue
        if label:
            points.append((label, value))
    if len(points) < 2:
        return ""
    top_label, top_value = max(points, key=lambda item: item[1])
    value_label = f"{top_value:.1%}" if 0 <= top_value <= 1 else f"{top_value:g}"
    metric = compact_whitespace(visual.y_label or value_key).replace("_", " ")
    return f"{top_label} ranks highest on {metric} at {value_label}"


def _first_row_key(rows: list[Any], candidates: tuple[str, ...]) -> str:
    sample = next((row for row in rows if isinstance(row, dict)), {})
    if not isinstance(sample, dict):
        return ""
    lower_to_key = {str(key).lower(): str(key) for key in sample.keys()}
    for candidate in candidates:
        if candidate.lower() in lower_to_key:
            return lower_to_key[candidate.lower()]
    return ""


def _first_numeric_row_key(rows: list[Any]) -> str:
    for row in rows:
        if not isinstance(row, dict):
            continue
        for key, value in row.items():
            try:
                float(value)
            except (TypeError, ValueError):
                continue
            return str(key)
    return ""


def _headlines_overlap(existing: str, evidence: str) -> bool:
    return _headline_overlap_count(existing, evidence) >= 2


def _headline_overlap_count(existing: str, evidence: str) -> int:
    existing_tokens = _meaningful_tokens(existing)
    evidence_tokens = _meaningful_tokens(evidence)
    return len(existing_tokens & evidence_tokens)


def _meaningful_tokens(value: Any) -> set[str]:
    generic = {
        "attrition",
        "employee",
        "employees",
        "worker",
        "workers",
        "rate",
        "risk",
        "risks",
        "analysis",
        "finding",
        "data",
    }
    tokens = {
        token
        for token in compact_whitespace(value).lower().replace("_", " ").split()
        if len(token.strip(".,:;()[]")) > 3
    }
    return {token.strip(".,:;()[]") for token in tokens if token.strip(".,:;()[]") not in generic}


def _findings_slide(workflow_state: dict[str, Any], legacy: dict[str, list[SlideSpec]]) -> SlideSpec:
    existing = _pop_legacy(legacy, "findings") or _pop_legacy(legacy, "summary")
    findings = _analysis_findings(workflow_state)
    tree_visual = _decision_tree_visual(workflow_state)
    has_eda_findings = _has_non_tree_evidence(workflow_state)
    if tree_visual and not has_eda_findings:
        top_rules = _decision_tree_rule_callouts(tree_visual)
        caveat = _decision_tree_caveat(tree_visual)
        findings = refine_bullets(top_rules + [caveat], max_items=4, max_chars=140)
        headline = "Exploratory tree rules define follow-up evidence"
        message = caveat or first_nonempty(*top_rules, "Use the tree rules as exploratory follow-up evidence.")
    else:
        headline = _findings_headline(workflow_state, findings)
        message = findings[0] if findings else "Use the visual analysis as the evidence base for the next decision."
    slide = SlideSpec(
        8,
        "findings",
        "three_finding_cards",
        headline,
        message,
        content_blocks=[
            ContentBlock(
                type="bullets",
                items=refine_bullets(
                    findings or ["No structured findings were captured for this run."],
                    max_items=4,
                ),
            )
        ],
    )
    if tree_visual and not has_eda_findings:
        return slide
    return _merge_slide(existing, slide)


def _has_non_tree_evidence(workflow_state: dict[str, Any]) -> bool:
    analysis = workflow_state.get("analysis_results", {}) or {}
    structured = list(analysis.get("analysis_artifacts", []) or []) + list(analysis.get("chart_specs", []) or [])
    if any(
        isinstance(item, dict)
        and compact_whitespace(item.get("chart_type")).lower() != "decision_tree"
        and any(compact_whitespace(item.get(key)) for key in ("finding", "takeaway", "title"))
        for item in structured
    ):
        return True
    captions = analysis.get("figure_captions", {}) or {}
    if isinstance(captions, dict) and any(compact_whitespace(value) for value in captions.values()):
        return True
    for item in analysis.get("business_findings", []) or []:
        text = compact_whitespace(item).lower()
        if text and "tree" not in text and "model rule" not in text:
            return True
    return False


def _business_translation_slide(workflow_state: dict[str, Any], legacy: dict[str, list[SlideSpec]]) -> SlideSpec:
    existing = _pop_legacy(legacy, "business_translation")
    business = workflow_state.get("agent_outputs", {}).get("business_translator", {}) or {}
    tree_visual = _decision_tree_visual(workflow_state)
    if tree_visual:
        segments = _decision_tree_intervention_bullets(tree_visual, workflow_state)
        if segments:
            slide = SlideSpec(
                9,
                "business_translation",
                "three_finding_cards",
                "Translate tree rules into intervention segments",
                "Use model rules to define segments, channels, and monitoring criteria for validation.",
                content_blocks=[ContentBlock(type="bullets", items=segments)],
            )
            return slide
    bullets = _business_translation_bullets(workflow_state, business)
    slide = SlideSpec(
        9,
        "business_translation",
        "comparison_matrix",
        _business_translation_headline(workflow_state),
        first_nonempty(business.get("executive_summary"), business.get("business_narrative"), "Business translation was not captured for this run."),
        content_blocks=[ContentBlock(type="bullets", items=bullets or ["Use the analysis findings as the primary business interpretation."])],
    )
    return _merge_slide(existing, slide)


def _business_translation_bullets(workflow_state: dict[str, Any], business: dict[str, Any]) -> list[str]:
    candidates = refine_bullets(
        business.get("key_findings", []) + business.get("opportunities", []) + business.get("immediate_actions", []),
        max_items=4,
        max_chars=150,
    )
    if _is_stock_time_series_context(workflow_state):
        first = candidates[0] if candidates else "Price, return, volatility, and volume evidence should guide bounded portfolio action."
        return [
            f"Decision use: {first}",
            "Tradeoff: pursue tactical entries only with drawdown and volatility guardrails.",
            "Operating rule: define entry, stop-loss, review cadence, and liquidity checks before acting.",
            "Validation: confirm current fundamentals and forward return behavior before scaling exposure.",
        ]
    if _is_lending_context(workflow_state):
        first = candidates[0] if candidates else "Credit-risk evidence should guide governed review rather than automated adverse action."
        return [
            f"Decision use: {first}",
            "Tradeoff: improve risk capture while monitoring false positives and fairness.",
            "Operating rule: route high-risk segments to human review with documented thresholds.",
            "Validation: track default capture, approval impact, fairness, and drift before scaling.",
        ]
    if candidates:
        labels = ("Decision use", "Tradeoff", "Operating rule", "Validation")
        return [f"{labels[index]}: {item}" for index, item in enumerate(candidates[:4])]
    return []


def _recommendations_slide(workflow_state: dict[str, Any], legacy: dict[str, list[SlideSpec]]) -> SlideSpec:
    existing = _pop_legacy(legacy, "recommendations")
    decision = workflow_state.get("agent_outputs", {}).get("decision_maker", {}) or {}
    business = workflow_state.get("agent_outputs", {}).get("business_translator", {}) or {}
    recommendations = decision.get("recommendations", []) or business.get("immediate_actions", []) or []
    bullets = _recommendation_slide_bullets(recommendations, workflow_state)
    slide = SlideSpec(
        10,
        "recommendations",
        "recommendation_priority",
        _recommendations_headline(workflow_state),
        _plain_limit(
            first_nonempty(decision.get("final_recommendation"), decision.get("executive_summary"), "Recommendations should be tied to the strongest available evidence."),
            max_words=18,
            max_chars=145,
        ),
        content_blocks=[ContentBlock(type="recommendations", items=bullets or ["Prioritize the strongest evidence-backed next action."])],
    )
    return _merge_slide(existing, slide)


def _limitations_slide(workflow_state: dict[str, Any], legacy: dict[str, list[SlideSpec]]) -> SlideSpec:
    existing = _pop_legacy(legacy, "limitations")
    objective = workflow_state.get("workflow_objective", {}) or {}
    business = workflow_state.get("agent_outputs", {}).get("business_translator", {}) or {}
    decision = workflow_state.get("agent_outputs", {}).get("decision_maker", {}) or {}
    analysis = workflow_state.get("analysis_results", {}) or {}
    warnings = workflow_state.get("analysis_artifact_warnings", []) or []
    decision_limits = decision.get("limitations", []) or decision.get("risks", []) or []
    decision_limit_details = _decision_limitation_details(decision_limits)
    summary_limits = _analysis_limitations(analysis.get("analysis_summary", {}) or {})
    tree_visual = _decision_tree_visual(workflow_state)
    model_caveat = _decision_tree_caveat(tree_visual) if tree_visual else ""
    bullets = _simple_slide_bullets(
        [model_caveat]
        + list(objective.get("limitations", []) if isinstance(objective, dict) else [])
        + decision_limit_details
        + business.get("risks", [])
        + summary_limits
        + warnings,
        max_items=5,
        max_chars=118,
    )
    if not bullets:
        bullets = ["Interpret observed relationships as decision evidence, not proof of causality.", "Validate recommendations with fresh data before operational rollout."]
    slide = SlideSpec(
        11,
        "limitations",
        "limitations_professional",
        _limitations_headline(workflow_state),
        "The deck separates supported evidence from areas that need validation.",
        content_blocks=[ContentBlock(type="limitations", items=bullets)],
    )
    return _merge_slide(existing, slide)


def _decision_limitation_details(items: Any) -> list[str]:
    details: list[str] = []
    for item in items if isinstance(items, list) else []:
        if not isinstance(item, dict):
            details.append(str(item))
            continue
        limitation = compact_whitespace(item.get("limitation") or item.get("risk"))
        mitigation = compact_whitespace(item.get("mitigation"))
        decision_impact = compact_whitespace(item.get("decision_impact"))
        if limitation:
            details.append(limitation)
        if mitigation:
            details.append(f"Mitigation: {mitigation}")
        elif decision_impact:
            details.append(f"Decision impact: {decision_impact}")
        if len(details) >= 4:
            break
    return details[:4]


def _summary_slide(workflow_state: dict[str, Any], legacy: dict[str, list[SlideSpec]]) -> SlideSpec:
    existing = _pop_legacy(legacy, "summary")
    decision = workflow_state.get("agent_outputs", {}).get("decision_maker", {}) or {}
    findings = _analysis_findings(workflow_state)
    bullets = refine_bullets(
        [
            findings[0] if findings else "",
            decision.get("final_recommendation", ""),
            decision.get("conclusion", ""),
        ],
        max_items=3,
    )
    slide = SlideSpec(
        12,
        "summary",
        "executive_summary_closing",
        _summary_headline(workflow_state),
        _summary_message(decision),
        content_blocks=[ContentBlock(type="bullets", items=bullets or ["Focus on the main finding, implication, and next action."])],
    )
    return _merge_slide(existing, slide)


def _findings_headline(workflow_state: dict[str, Any], findings: list[str]) -> str:
    if _is_stock_time_series_context(workflow_state):
        return "Price, volatility, and volume define the evidence base"
    return refine_headline("", first_nonempty(*findings, "Evidence findings define the next decision"))


def _business_translation_headline(workflow_state: dict[str, Any]) -> str:
    if _is_stock_time_series_context(workflow_state):
        return "Price regime evidence translates into portfolio choices"
    if _is_lending_context(workflow_state):
        return "Credit-risk evidence translates into governed review choices"
    return "Evidence patterns translate into clear business choices"


def _recommendations_headline(workflow_state: dict[str, Any]) -> str:
    if _is_stock_time_series_context(workflow_state):
        return "Use triggers, validation gates, and review cadence"
    if _is_lending_context(workflow_state):
        return "Prioritize governed validation pilots before policy changes"
    return "Prioritized actions convert evidence into execution choices"


def _limitations_headline(workflow_state: dict[str, Any]) -> str:
    if _is_stock_time_series_context(workflow_state):
        return "Validation gates keep price actions evidence-led"
    return "Limitations define the next validation checks"


def _summary_headline(workflow_state: dict[str, Any]) -> str:
    if _is_stock_time_series_context(workflow_state):
        return "Act only when price and volatility triggers align"
    return "Act on the clearest evidence with validation gates"


def _merge_slide(existing: SlideSpec | None, fallback: SlideSpec) -> SlideSpec:
    if not existing:
        return fallback
    fallback.headline = refine_headline(existing.headline, fallback.headline)
    fallback.main_message = first_nonempty(existing.main_message, fallback.main_message)
    fallback.subtitle = first_nonempty(existing.subtitle, fallback.subtitle)
    if existing.content_blocks:
        fallback.content_blocks = existing.content_blocks
    if existing.visual:
        if fallback.visual and fallback.visual.type == "code_figure":
            pass
        elif fallback.visual and fallback.visual.type in {"structured_chart", "chart"}:
            if existing.visual.type in {"image", "legacy_image_fallback"}:
                pass
            elif existing.visual.type in {"structured_chart", "chart"} and _visual_has_data(existing.visual):
                fallback.visual = existing.visual
        else:
            if _legacy_visual_can_attach(existing.visual, fallback):
                fallback.visual = existing.visual
    if existing.metrics:
        fallback.metrics = existing.metrics
    return fallback


def _polish_deck_slides(deck: DeckSpec) -> None:
    for slide in deck.slides:
        _align_slide_text_to_visual(slide)
        slide.headline = _limit_words(soften_unsupported_impact_claim(slide.headline), max_words=14, max_chars=92)
        if slide.slide_role in {"recommendations", "limitations"}:
            slide.main_message = _plain_limit(slide.main_message, max_words=20, max_chars=150)
        else:
            slide.main_message = _limit_words(soften_unsupported_impact_claim(slide.main_message), max_words=24, max_chars=170)
        slide.subtitle = shorten(slide.subtitle, 120)
        for block in slide.content_blocks:
            max_chars = 190 if block.type == "recommendations" else 126
            if block.type in {"recommendations", "limitations"}:
                block.items = _dedupe_text_items(
                    _plain_limit(item, max_words=34 if block.type == "recommendations" else 14, max_chars=max_chars)
                    for item in block.items
                )
            else:
                block.items = _dedupe_text_items(
                    _limit_words(soften_unsupported_impact_claim(item), max_words=18, max_chars=max_chars)
                    for item in block.items
                )
        if slide.visual and slide.visual.chart_type == "decision_tree":
            data = slide.visual.data if isinstance(slide.visual.data, dict) else {}
            note = _decision_tree_caveat(slide.visual)
            if note:
                slide.visual.takeaway = _limit_words(note, max_words=24, max_chars=170)
                if not slide.main_message or "baseline" in note.lower():
                    slide.main_message = _limit_words(note, max_words=24, max_chars=170)


def _legacy_visual_can_attach(visual: VisualSpec, slide: SlideSpec) -> bool:
    if slide.slide_role == "analysis":
        return True
    if visual.type in {"structured_chart", "chart", "code_figure"} or visual.chart_type == "decision_tree":
        return _slide_matches_visual(slide, visual)
    return visual.type in {"image", "legacy_image_fallback"}


def _align_slide_text_to_visual(slide: SlideSpec) -> None:
    visual = slide.visual
    if not visual:
        return
    if visual.type not in {"structured_chart", "chart", "code_figure"} and visual.chart_type != "decision_tree":
        return
    if visual.chart_type == "decision_tree":
        headline = _decision_tree_visual_headline(visual)
        data = visual.data if isinstance(visual.data, dict) else {}
        note = _decision_tree_caveat(visual)
        if headline:
            slide.headline = headline
            visual.finding = headline
        if note:
            visual.takeaway = note
            slide.main_message = note
        elif visual.takeaway:
            slide.main_message = visual.takeaway
        if slide.content_blocks:
            items = [item for item in (headline, note or visual.takeaway, visual.title) if compact_whitespace(item)]
            slide.content_blocks[0].items = _dedupe_text_items(items)
        return
    evidence_text = _visual_evidence_text(visual)
    if not evidence_text:
        return
    if visual.type == "code_figure" and _headline_has_unsupported_ratio(slide.headline, evidence_text):
        slide.headline = refine_headline("", evidence_text)
    elif not _headlines_overlap(slide.headline, evidence_text):
        slide.headline = refine_headline("", evidence_text)
    if slide.main_message and _headlines_overlap(slide.main_message, evidence_text):
        return
    slide.main_message = shorten(first_nonempty(visual.finding, visual.takeaway, visual.title, evidence_text), 170)


def _slide_matches_visual(slide: SlideSpec, visual: VisualSpec) -> bool:
    slide_text = " ".join(
        [
            compact_whitespace(slide.headline),
            compact_whitespace(slide.main_message),
            " ".join(item for block in slide.content_blocks for item in block.items),
        ]
    )
    return _headlines_overlap(slide_text, _visual_evidence_text(visual))


def _visual_evidence_text(visual: VisualSpec) -> str:
    data_text = ""
    if isinstance(visual.data, dict):
        data_text = " ".join(
            compact_whitespace(visual.data.get(key))
            for key in ("performance_note", "metric_label", "target", "target_column")
            if compact_whitespace(visual.data.get(key))
        )
    return first_nonempty(visual.finding, visual.takeaway, visual.title, data_text)


def _decision_tree_visual_headline(visual: VisualSpec) -> str:
    data = visual.data if isinstance(visual.data, dict) else {}
    nodes = data.get("nodes", []) if isinstance(data, dict) else []
    source_ids = {
        compact_whitespace(edge.get("source") or edge.get("from") or edge.get("parent"))
        for edge in data.get("edges", [])
        if isinstance(edge, dict)
    }
    features: list[str] = []
    for node in nodes:
        if not isinstance(node, dict):
            continue
        node_id = compact_whitespace(node.get("id") or node.get("node_id") or node.get("name"))
        if compact_whitespace(node.get("type")).lower() != "split" and node_id not in source_ids:
            continue
        feature = compact_whitespace(node.get("feature"))
        if not feature:
            label = compact_whitespace(node.get("label") or node.get("rule"))
            feature = re_split_feature(label)
        feature = _clean_tree_feature_name(feature)
        key = feature.lower()
        if feature and key not in {item.lower() for item in features}:
            features.append(feature)
        if len(features) >= 3:
            break
    if features:
        joined = _join_short_list(features)
        note = _decision_tree_caveat(visual).lower()
        prefix = "Exploratory tree splits" if any(token in note for token in ("explanatory", "baseline", "imbalance", "precision")) else "Decision tree splits"
        return f"{prefix} on {joined}"
    return first_nonempty(visual.title, "Decision tree rules summarize model logic")


def _decision_tree_caveat(visual: VisualSpec | None) -> str:
    if not visual:
        return ""
    data = visual.data if isinstance(visual.data, dict) else {}
    return first_nonempty(
        decision_tree_imbalance_note(data),
        data.get("performance_note"),
        decision_tree_performance_note(data),
        "Exploratory screening only: validate precision, recall, F1, and support before operational use.",
    )


def _decision_tree_visual(workflow_state: dict[str, Any]) -> VisualSpec | None:
    analysis = workflow_state.get("analysis_results", {}) or {}
    for artifact in list(analysis.get("analysis_artifacts", []) or []) + list(analysis.get("chart_specs", []) or []):
        if isinstance(artifact, dict) and compact_whitespace(artifact.get("chart_type")).lower() == "decision_tree":
            visual = VisualSpec.from_any({"type": "structured_chart", **artifact})
            if visual and isinstance(visual.data, dict):
                target = compact_whitespace(workflow_state.get("decision_tree_target_column"))
                if target and not compact_whitespace(visual.data.get("target") or visual.data.get("target_column")):
                    visual.data["target"] = target
            return visual
    return None


def _decision_tree_rule_callouts(visual: VisualSpec | None, limit: int = 3) -> list[str]:
    if not visual or not isinstance(visual.data, dict):
        return []
    nodes = [node for node in visual.data.get("nodes", []) if isinstance(node, dict)]
    edges = [edge for edge in visual.data.get("edges", []) if isinstance(edge, dict)]
    parent_by_child = {compact_whitespace(edge.get("target") or edge.get("to") or edge.get("child")): edge for edge in edges}
    node_by_id = {compact_whitespace(node.get("id") or node.get("node_id") or node.get("name")): node for node in nodes}
    callouts: list[str] = []
    for node_id, node in node_by_id.items():
        if compact_whitespace(node.get("type")).lower() != "leaf" and "predict" not in compact_whitespace(node.get("label")).lower():
            continue
        edge = parent_by_child.get(node_id, {})
        parent = node_by_id.get(compact_whitespace(edge.get("source") or edge.get("from") or edge.get("parent")), {})
        condition = compact_whitespace(edge.get("condition") or edge.get("label"))
        split = compact_whitespace(parent.get("label") or parent.get("rule"))
        prediction = compact_whitespace(node.get("prediction") or node.get("label") or node.get("rule"))
        text = " | ".join(part for part in (split, condition, prediction) if part)
        if text:
            callouts.append(text)
        if len(callouts) >= limit:
            break
    if callouts:
        return [_business_rule_callout(callout, visual) for callout in callouts]
    rules = visual.data.get("rules", [])
    return [_business_rule_callout(rule, visual) for rule in rules if compact_whitespace(rule)][:limit]


def _decision_tree_intervention_bullets(visual: VisualSpec | None, workflow_state: dict[str, Any] | None = None) -> list[str]:
    if not visual:
        return []
    workflow_state = workflow_state or {}
    features = _decision_tree_split_features_from_visual(visual)
    target = compact_whitespace(workflow_state.get("decision_tree_target_column")).lower()
    description = compact_whitespace(workflow_state.get("user_data_description")).lower()
    if "attrition" in target or "attrition" in description:
        subject = "employees"
        review_channel = "manager and HR review"
    elif "depression" in target or "mental health" in description:
        subject = "students"
        review_channel = "counselor review"
    else:
        subject = "records"
        review_channel = "owner review"
    if any(token in target or token in description for token in ("loan", "credit", "default")):
        subject = "applications"
        review_channel = "underwriting or portfolio review"
    bullets: list[str] = []
    if features:
        bullets.append(f"Segment {subject} by model-extracted rule fields: {', '.join(features[:3])}.")
    bullets.append(f"Use {review_channel} as the channel for high-risk rule segments.")
    if any(token in target or token in description for token in ("loan", "credit", "default")):
        bullets.append("Track default capture, false-positive review rate, approval impact, and fairness before scaling.")
    else:
        bullets.append("Monitor precision, recall, F1, and positive-class support before scaling.")
    return refine_bullets(bullets, max_items=3, max_chars=130)


def _business_rule_callout(rule: Any, visual: VisualSpec) -> str:
    text = compact_whitespace(rule)
    if not text:
        return ""
    text = re.sub(r"\bIf\s+", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\bthen\s+predict\s+", "=> predicted ", text, flags=re.IGNORECASE)
    text = text.replace("[Default]", "higher default risk").replace("[No Default]", "lower default risk")
    text = re.sub(r"\[(1|Yes|True)\]", "higher default risk", text, flags=re.IGNORECASE)
    text = re.sub(r"\[(0|No|False)\]", "lower default risk", text, flags=re.IGNORECASE)
    text = text.replace("_", " ")
    text = re.sub(r"\s+", " ", text).strip(" .")
    target = compact_whitespace(visual.data.get("target") if isinstance(visual.data, dict) else "").lower()
    if any(token in target for token in ("loan", "default", "credit")):
        text = _credit_rule_language(text)
    return shorten(text, 138, placeholder="")


def _credit_rule_language(text: str) -> str:
    replacements = {
        "loan percent income": "debt burden",
        "loan percent income": "debt burden",
        "loan_percent_income": "debt burden",
        "loan int rate": "interest rate",
        "loan_int_rate": "interest rate",
        "person income": "borrower income",
        "person_income": "borrower income",
        "loan grade": "loan grade",
        "loan_grade": "loan grade",
        "person home ownership": "home ownership",
        "person_home_ownership": "home ownership",
        "cb person default on file": "prior default flag",
        "cb_person_default_on_file": "prior default flag",
    }
    clean = text
    for source, replacement in replacements.items():
        clean = re.sub(source, replacement, clean, flags=re.IGNORECASE)
    clean = re.sub(r"borrower income\s*<=\s*(\d+(?:\.\d+)?)", lambda m: f"borrower income at or below ${float(m.group(1)):,.0f}", clean, flags=re.IGNORECASE)
    clean = re.sub(r"borrower income\s*>\s*(\d+(?:\.\d+)?)", lambda m: f"borrower income above ${float(m.group(1)):,.0f}", clean, flags=re.IGNORECASE)
    clean = re.sub(r"debt burden\s*<=\s*(\d+(?:\.\d+)?)", r"debt burden at or below \1", clean, flags=re.IGNORECASE)
    clean = re.sub(r"debt burden\s*>\s*(\d+(?:\.\d+)?)", r"debt burden above \1", clean, flags=re.IGNORECASE)
    clean = clean.replace("<=", "at or below").replace(">=", "at least").replace(">", "above").replace("<", "below")
    return compact_whitespace(clean)


def _decision_tree_split_features_from_visual(visual: VisualSpec) -> list[str]:
    data = visual.data if isinstance(visual.data, dict) else {}
    nodes = data.get("nodes", []) if isinstance(data, dict) else []
    source_ids = {
        compact_whitespace(edge.get("source") or edge.get("from") or edge.get("parent"))
        for edge in data.get("edges", [])
        if isinstance(edge, dict)
    }
    features: list[str] = []
    for node in nodes:
        if not isinstance(node, dict):
            continue
        node_id = compact_whitespace(node.get("id") or node.get("node_id") or node.get("name"))
        if compact_whitespace(node.get("type")).lower() != "split" and node_id not in source_ids:
            continue
        feature = compact_whitespace(node.get("feature")) or re_split_feature(compact_whitespace(node.get("label") or node.get("rule")))
        feature = _clean_tree_feature_name(feature)
        if feature and feature.lower() not in {item.lower() for item in features}:
            features.append(feature)
        if len(features) >= 3:
            break
    return features


def _remove_unverified_ratio_claim(text: Any) -> str:
    clean = compact_whitespace(text)
    return re.sub(r"\b\d+(?:\.\d+)?x\s+(?:higher|lower|greater|larger|smaller)\b", "different", clean, flags=re.IGNORECASE)


def re_split_feature(label: str) -> str:
    for marker in ("<=", ">=", "<", ">", "="):
        if marker in label:
            return compact_whitespace(label.split(marker, 1)[0])
    return ""


def _clean_tree_feature_name(feature: str) -> str:
    text = compact_whitespace(feature).replace("_", " ")
    for suffix in (" Yes", " No", " True", " False", " 1", " 0"):
        if text.endswith(suffix):
            text = text[: -len(suffix)]
            break
    return compact_whitespace(text)


def _join_short_list(items: list[str]) -> str:
    if len(items) <= 1:
        return items[0] if items else ""
    if len(items) == 2:
        return f"{items[0]} and {items[1]}"
    return f"{', '.join(items[:-1])}, and {items[-1]}"


def _limit_words(value: Any, *, max_words: int, max_chars: int) -> str:
    text = soften_unsupported_impact_claim(value)
    if not text:
        return ""
    words = text.split()
    if len(words) > max_words:
        text = " ".join(words[:max_words]).rstrip(".,;:")
        if text:
            text += "."
    return shorten(text, max_chars)


def _plain_limit(value: Any, *, max_words: int, max_chars: int) -> str:
    text = soften_unsupported_impact_claim(value).rstrip(".")
    if not text:
        return ""
    words = text.split()
    if len(words) > max_words:
        text = " ".join(words[:max_words]).rstrip(".,;:")
    if len(text) > max_chars:
        text = text[:max_chars].rsplit(" ", 1)[0].rstrip(".,;:")
    return compact_whitespace(text)


def _simple_slide_bullets(items: Any, *, max_items: int, max_chars: int) -> list[str]:
    bullets = refine_bullets(items, max_items=max_items, max_chars=max_chars + 40)
    return [_plain_limit(item, max_words=14, max_chars=max_chars) for item in bullets if compact_whitespace(item)]


def _recommendation_slide_bullets(recommendations: Any, workflow_state: dict[str, Any]) -> list[str]:
    if not recommendations:
        if _is_stock_time_series_context(workflow_state):
            return [
                "Action: monitor price triggers. Owner: investment lead. Trigger: volatility or drawdown breach. Guardrail: forward return and liquidity review."
            ]
        return ["Action: run validation pilots. Owner: process owner. Trigger: highest-risk segment. Guardrail: outcome and false-positive review."]
    if not isinstance(recommendations, (list, tuple)):
        recommendations = [recommendations]
    lending = _is_lending_context(workflow_state)
    stock = _is_stock_time_series_context(workflow_state)
    default_targets = [
        "high debt-burden applicants",
        "weaker-grade or high-interest applications",
        "prior-default or low-income review segments",
    ]
    caveats = [
        "Caveat: monitor approval-rate and fairness impact.",
        "Caveat: keep human review before adverse decisions.",
        "Caveat: recalibrate if portfolio mix changes.",
    ]
    bullets: list[str] = []
    for index, item in enumerate(recommendations[:3]):
        if isinstance(item, dict):
            action = compact_whitespace(item.get("action")) or "Run a targeted validation pilot"
            target = compact_whitespace(item.get("target_segment") or item.get("segment") or item.get("who"))
            evidence = compact_whitespace(item.get("evidence")) or "supported by analysis signals"
            metric = compact_whitespace(item.get("validation_metric") or item.get("metric"))
            owner = compact_whitespace(item.get("owner") or item.get("accountable_owner"))
            trigger = compact_whitespace(item.get("trigger") or item.get("threshold"))
            caveat = compact_whitespace(item.get("caveat"))
        else:
            action = compact_whitespace(item) or "Run a targeted validation pilot"
            target = ""
            evidence = "supported by analysis signals"
            metric = ""
            owner = ""
            trigger = ""
            caveat = ""
        if lending:
            target = target or default_targets[index % len(default_targets)]
            metric = metric or "default capture, false-positive review rate, approval impact"
            owner = owner or "risk owner"
            trigger = trigger or "segment crosses the defined risk threshold"
        elif stock:
            stock_targets = [
                "price breakouts near support or resistance",
                "high-volatility or drawdown windows",
                "volume and liquidity spikes",
            ]
            target = target or stock_targets[index % len(stock_targets)]
            metric = metric or "forward return, drawdown, volatility, volume, and liquidity"
            owner = owner or "investment lead"
            trigger = trigger or "price, volatility, or volume signal crosses the review threshold"
            caveat = caveat or "Caveat: validate against current market conditions before trading."
        else:
            target = target or "highest-risk segment"
            metric = metric or "pilot outcome lift and false-positive rate"
            owner = owner or "business owner"
            trigger = trigger or "segment enters the agreed intervention threshold"
        caveat = caveat or caveats[index % len(caveats)]
        bullets.append(f"Action: {action}. Owner: {owner}. Trigger: {trigger}. Guardrail: {metric}. Target: {target}. {caveat}")
    return [_plain_limit(item, max_words=34, max_chars=240) for item in bullets]


def _summary_message(decision: dict[str, Any]) -> str:
    message = first_nonempty(
        decision.get("conclusion"),
        decision.get("final_recommendation"),
        "Use the strongest finding as the next decision checkpoint.",
    )
    message = soften_unsupported_impact_claim(message)
    if re.search(r"\breduc(?:e|es|ing)\s+(credit\s+)?loss", message, flags=re.IGNORECASE):
        return "Run validation pilots on risk segments before claiming credit-loss reduction."
    return message


def _is_lending_context(workflow_state: dict[str, Any] | None) -> bool:
    if not workflow_state:
        return False
    outputs = workflow_state.get("agent_outputs", {}) or {}
    data = outputs.get("data_understander", {}) if isinstance(outputs, dict) else {}
    fields: list[str] = []
    for dataset in (data.get("datasets", {}) or {}).values() if isinstance(data, dict) else []:
        if isinstance(dataset, dict):
            fields.extend(str(field) for field in dataset.get("columns", [])[:30])
    text = " ".join(
        [
            compact_whitespace(workflow_state.get("decision_tree_target_column")),
            compact_whitespace(workflow_state.get("data_description")),
            compact_whitespace(workflow_state.get("user_data_description")),
            " ".join(fields),
        ]
    ).lower()
    return any(token in text for token in ("loan_status", "loan status", "loan_", "credit", "default", "underwriting"))


def _is_stock_time_series_context(workflow_state: dict[str, Any] | None) -> bool:
    if not workflow_state:
        return False
    outputs = workflow_state.get("agent_outputs", {}) or {}
    data = outputs.get("data_understander", {}) if isinstance(outputs, dict) else {}
    fields: list[str] = []
    names: list[str] = []
    for dataset_name, dataset in (data.get("datasets", {}) or {}).items() if isinstance(data, dict) else []:
        names.append(str(dataset_name))
        if isinstance(dataset, dict):
            fields.extend(str(field) for field in dataset.get("columns", [])[:30])
    if not fields:
        for df in (workflow_state.get("csv_data", {}) or {}).values():
            fields.extend(str(field) for field in getattr(df, "columns", [])[:30])
            break
    description_text = " ".join(
        [
            compact_whitespace(workflow_state.get("data_description")),
            compact_whitespace(workflow_state.get("user_data_description")),
            " ".join(names),
        ]
    ).lower()
    return bool(re.search(r"\b(stock|share price|ohlc|stc)\b", description_text)) or _looks_like_stock_fields(fields)


def _dedupe_text_items(items: Any) -> list[str]:
    unique: list[str] = []
    seen: set[str] = set()
    for item in items:
        text = compact_whitespace(item)
        if not text:
            continue
        key = "".join(ch.lower() for ch in text if ch.isalnum() or ch.isspace()).strip()
        if _near_duplicate_text_key(key, seen):
            continue
        seen.add(key)
        unique.append(text)
    return unique


def _near_duplicate_text_key(key: str, seen: set[str]) -> bool:
    if not key:
        return True
    for existing in seen:
        if key == existing:
            return True
        shorter, longer = sorted((key, existing), key=len)
        if len(shorter) >= 42 and longer.startswith(shorter):
            return True
        if len(shorter) >= 42 and shorter in longer:
            return True
        key_tokens = set(shorter.split())
        existing_tokens = set(longer.split())
        if len(key_tokens) >= 6 and len(key_tokens & existing_tokens) / max(len(key_tokens), 1) >= 0.82:
            return True
    return False


def _analysis_artifact_queue(workflow_state: dict[str, Any]) -> list[VisualSpec]:
    visuals: list[VisualSpec] = []
    seen: set[str] = set()
    seen_visual_signatures: set[str] = set()
    invalid_structured_visuals: list[str] = []
    analysis = workflow_state.get("analysis_results", {}) or {}
    captions = analysis.get("figure_captions", {}) or {}
    structured_sources = list(analysis.get("analysis_artifacts", []) or []) + list(analysis.get("chart_specs", []) or [])
    has_decision_tree = any(
        isinstance(spec, dict) and compact_whitespace(spec.get("chart_type")).lower() == "decision_tree"
        for spec in structured_sources
    )
    non_tree_sources = [
        spec
        for spec in structured_sources
        if not (isinstance(spec, dict) and compact_whitespace(spec.get("chart_type")).lower() == "decision_tree")
    ]
    non_tree_sources = sorted(non_tree_sources, key=_analysis_visual_priority)
    tree_sources = [
        spec
        for spec in structured_sources
        if isinstance(spec, dict) and compact_whitespace(spec.get("chart_type")).lower() == "decision_tree"
    ]
    figure_paths = list(workflow_state.get("saved_figures", []) or analysis.get("figures_generated", []) or [])
    figure_paths = sorted(
        figure_paths,
        key=lambda path: _figure_visual_priority(workflow_state, path, _caption_for_figure(path, captions)),
    )
    max_code_figures = 3 if has_decision_tree and tree_sources else 4
    for path in figure_paths:
        if len(visuals) >= max_code_figures:
            break
        if not path or not Path(str(path)).exists() or str(path) in seen:
            continue
        if has_decision_tree and Path(str(path)).name.lower().startswith("decision_tree_rules"):
            continue
        caption = _caption_for_figure(path, captions)
        matched_artifact = _match_figure_artifact(caption, structured_sources)
        visual = VisualSpec(
            type="code_figure",
            chart_type=compact_whitespace(matched_artifact.get("chart_type")) or "code_figure",
            artifact_id=compact_whitespace(matched_artifact.get("artifact_id") or matched_artifact.get("id")),
            chart_spec_id=compact_whitespace(matched_artifact.get("artifact_id") or matched_artifact.get("id")),
            title=_figure_title(path, caption),
            takeaway=shorten(matched_artifact.get("takeaway") or caption, 150),
            finding=shorten(matched_artifact.get("finding") or caption, 180),
            image_path=str(path),
        )
        if _append_analysis_visual(visual, visuals, seen, seen_visual_signatures, key=str(path)):
            continue
    non_tree_sources = sorted(non_tree_sources, key=_visual_relevance_score, reverse=True)
    ordered_structured_sources: list[Any] = []
    if has_decision_tree:
        non_tree_slots = max(3 - len(visuals), 0)
        ordered_structured_sources.extend(non_tree_sources[:non_tree_slots])
        ordered_structured_sources.extend(tree_sources[:1])
        ordered_structured_sources.extend(non_tree_sources[non_tree_slots:])
        ordered_structured_sources.extend(tree_sources[1:])
    else:
        ordered_structured_sources = non_tree_sources
    for spec in ordered_structured_sources:
        if len(visuals) >= 4:
            break
        if (
            isinstance(spec, dict)
            and compact_whitespace(spec.get("chart_type")).lower() == "decision_tree"
            and _decision_tree_structured_valid(spec)
        ):
            visual = VisualSpec.from_any({"type": "structured_chart", **spec})
        elif isinstance(spec, dict) and compact_whitespace(spec.get("chart_type")).lower() == "decision_tree" and _artifact_image_path(spec):
            visual = VisualSpec.from_any({"type": "code_figure", **spec})
        elif isinstance(spec, dict) and _artifact_image_path(spec):
            image_path = _artifact_image_path(spec)
            visual = VisualSpec.from_any({"type": "code_figure", **spec, "image_path": image_path})
        else:
            visual = VisualSpec.from_any({"type": "structured_chart", **spec}) if isinstance(spec, dict) else None
        if visual:
            key = visual.artifact_id or visual.chart_spec_id or visual.title or str(len(visuals))
            if visual.type == "code_figure" and visual.image_path and Path(visual.image_path).exists():
                _append_analysis_visual(visual, visuals, seen, seen_visual_signatures, key=key)
                continue
            if not has_structured_chart_data(visual):
                invalid_structured_visuals.append(key)
                continue
            if visual.recommended_template not in TEMPLATE_REGISTRY:
                visual.recommended_template = _template_for_chart_type(visual.chart_type)
            _append_analysis_visual(visual, visuals, seen, seen_visual_signatures, key=key)
    if invalid_structured_visuals:
        workflow_state.setdefault("slide_validation_warnings", []).append(
            {
                "scope": "deck",
                "issue": "structured_chart_data_missing",
                "artifact_ids": invalid_structured_visuals[:5],
            }
        )
    if visuals:
        if len(visuals) < 4:
            workflow_state.setdefault("slide_validation_warnings", []).append(
                {
                    "scope": "deck",
                    "issue": "analysis_visual_shortfall",
                    "expected": 4,
                    "available": len(visuals),
                }
            )
        return visuals

    return visuals


def _match_figure_artifact(caption: str, artifacts: list[Any]) -> dict[str, Any]:
    caption_tokens = _meaningful_tokens(caption)
    best: dict[str, Any] = {}
    best_score = 0.0
    for item in artifacts:
        if not isinstance(item, dict) or compact_whitespace(item.get("chart_type")).lower() == "decision_tree":
            continue
        candidate = " ".join(
            compact_whitespace(item.get(key)) for key in ("title", "finding", "takeaway") if compact_whitespace(item.get(key))
        )
        candidate_tokens = _meaningful_tokens(candidate)
        if not caption_tokens or not candidate_tokens:
            continue
        score = len(caption_tokens & candidate_tokens) / max(1, min(len(caption_tokens), len(candidate_tokens)))
        if score > best_score:
            best, best_score = item, score
    return best if best_score >= 0.22 else {}


def _append_analysis_visual(
    visual: VisualSpec,
    visuals: list[VisualSpec],
    seen: set[str],
    seen_visual_signatures: set[str],
    *,
    key: str = "",
) -> bool:
    dedupe_key = compact_whitespace(key) or visual.artifact_id or visual.chart_spec_id or visual.image_path or visual.title or str(len(visuals))
    if dedupe_key in seen:
        return False
    image_key = compact_whitespace(visual.image_path)
    if image_key and image_key in seen:
        return False
    signature = _visual_semantic_signature(visual)
    if signature and signature in seen_visual_signatures:
        return False
    seen.add(dedupe_key)
    if image_key:
        seen.add(image_key)
    if signature:
        seen_visual_signatures.add(signature)
    visuals.append(visual)
    return True


def _visual_semantic_signature(visual: VisualSpec) -> str:
    title = compact_whitespace(visual.title).lower()
    if title:
        title = re.sub(r"[^a-z0-9\s]", " ", title)
        title = re.sub(r"\s+", " ", title).strip()
        return f"{compact_whitespace(visual.chart_type).lower()}:{title}"
    fields = " ".join(
        compact_whitespace(value).lower()
        for value in (visual.chart_type, visual.x, visual.y, visual.group_by, visual.finding, visual.takeaway)
        if compact_whitespace(value)
    )
    fields = re.sub(r"[^a-z0-9\s]", " ", fields)
    return re.sub(r"\s+", " ", fields).strip()


def _artifact_image_path(spec: dict[str, Any]) -> str:
    for key in ("image_path", "fallback_path", "visual_path"):
        path = compact_whitespace(spec.get(key))
        if path and Path(path).exists():
            return path
    data = spec.get("data", {}) if isinstance(spec.get("data"), dict) else {}
    for key in ("image_path", "fallback_path", "figure_path"):
        path = compact_whitespace(data.get(key))
        if path and Path(path).exists():
            return path
    return ""


def _analysis_visual_priority(spec: Any) -> int:
    if not isinstance(spec, dict):
        return 50
    text = " ".join(
        compact_whitespace(spec.get(key))
        for key in ("artifact_id", "title", "finding", "takeaway", "x", "y", "group_by", "chart_type")
    ).lower()
    preferred = (
        "loan_grade",
        "loan grade",
        "debt burden",
        "loan_percent_income",
        "percent income",
        "income band",
        "interest",
        "loan_int_rate",
        "default",
        "home ownership",
    )
    hr_preferred = (
        "department",
        "overtime",
        "job satisfaction",
        "environment satisfaction",
        "work life balance",
        "monthly income",
        "sales representative",
        "years at company",
    )
    weak = ("age", "person_age", "scatter")
    if "multi-panel" in text or "small multiple" in text or "segment chart" in text:
        return 30
    if "volume-return" in text or ("scatter" in text and "correlation" in text):
        return 25
    if any(token in text for token in ("stock", "price", "volatility", "drawdown", "moving average", "seasonal", "return distribution", "volume spike")):
        return 0
    if any(token in text for token in preferred):
        return 0
    if any(token in text for token in hr_preferred):
        return 0
    if any(token in text for token in weak):
        return 20
    return 10


def _visual_relevance_score(spec: Any) -> int:
    if not isinstance(spec, dict):
        return 0
    text = " ".join(
        compact_whitespace(spec.get(key)).lower()
        for key in ("artifact_id", "id", "chart_type", "title", "finding", "takeaway", "x", "y", "group_by")
    )
    score = 0
    for token, weight in (
        ("price trend", 10),
        ("moving average", 10),
        ("volatility", 9),
        ("drawdown", 9),
        ("seasonal", 7),
        ("return distribution", 7),
        ("volume spike", 6),
        ("default", 10),
        ("attrition", 10),
        ("depression", 10),
        ("risk", 8),
        ("target", 7),
        ("loan grade", 7),
        ("previous default", 7),
        ("loan percent income", 6),
        ("department", 7),
        ("overtime", 7),
        ("job satisfaction", 7),
        ("environment satisfaction", 6),
        ("work life balance", 6),
        ("sales representative", 6),
        ("years at company", 5),
        ("interest", 5),
        ("income", 4),
        ("rate", 3),
    ):
        if token in text:
            score += weight
    if "age" in text and not any(token in text for token in ("default", "attrition", "depression", "risk")):
        score -= 6
    if "multi-panel" in text or "small multiple" in text or "segment chart" in text:
        score -= 10
    if "scatter" in text or "volume-return" in text or "correlation" in text:
        score -= 8
    return score


def _figure_visual_priority(workflow_state: dict[str, Any], figure: Any, caption: str) -> int:
    text = f"{Path(str(figure)).name} {caption}".lower()
    if _is_stock_time_series_context(workflow_state):
        if any(token in text for token in ("price trend", "moving average", "support", "resistance")):
            return 0
        if any(token in text for token in ("volume spike", "volume trend", "price-volume", "liquidity")):
            return 1
        if any(token in text for token in ("return distribution", "daily return", "seasonal", "monthly return")):
            return 2
        if any(token in text for token in ("volatility", "drawdown")):
            return 3
        if any(token in text for token in ("scatter", "volume-return", "correlation")):
            return 25
    if _is_lending_context(workflow_state):
        return _analysis_visual_priority({"title": text, "chart_type": "code_figure"})
    return 10


def _decision_tree_structured_valid(spec: dict[str, Any]) -> bool:
    data = spec.get("data", {}) if isinstance(spec.get("data"), dict) else {}
    nodes = [node for node in data.get("nodes", []) if isinstance(node, dict)]
    edges = [edge for edge in data.get("edges", []) if isinstance(edge, dict)]
    if not nodes or not edges:
        return False
    node_ids = {compact_whitespace(node.get("id") or node.get("node_id") or node.get("name")) for node in nodes}
    source_ids = {compact_whitespace(edge.get("source") or edge.get("from") or edge.get("parent")) for edge in edges}
    target_ids = {compact_whitespace(edge.get("target") or edge.get("to") or edge.get("child")) for edge in edges}
    leaves = [
        node
        for node in nodes
        if compact_whitespace(node.get("id") or node.get("node_id") or node.get("name")) not in source_ids
    ]
    has_split = any(
        compact_whitespace(node.get("type")).lower() == "split"
        or compact_whitespace(node.get("id") or node.get("node_id") or node.get("name")) in source_ids
        for node in nodes
    )
    return bool(node_ids and target_ids.issubset(node_ids) and has_split and len(leaves) >= 2)


def _caption_for_figure(path: Any, captions: dict[str, Any]) -> str:
    if not isinstance(captions, dict):
        return ""
    figure_path = Path(str(path))
    for key in (path, str(path), figure_path.name, figure_path.stem):
        text = compact_whitespace(captions.get(key))
        if text:
            return text
    return ""


def _figure_title(path: Any, caption: str) -> str:
    if caption:
        first_sentence = caption.split(". ", 1)[0].strip().rstrip(".")
        if first_sentence:
            return shorten(first_sentence, 80)
    return Path(str(path)).stem.replace("_", " ").title()


def _visual_has_data(visual: VisualSpec) -> bool:
    if isinstance(visual.data, list) and visual.data:
        return True
    if isinstance(visual.data, dict) and any(isinstance(visual.data.get(key), list) and visual.data.get(key) for key in ("rows", "data", "values")):
        return True
    if isinstance(visual.series, list) and visual.series:
        return True
    return False


def _analysis_findings(workflow_state: dict[str, Any]) -> list[str]:
    analysis = workflow_state.get("analysis_results", {}) or {}
    findings: list[str] = []
    tree_present = any(
        isinstance(artifact, dict) and compact_whitespace(artifact.get("chart_type")).lower() == "decision_tree"
        for artifact in (analysis.get("analysis_artifacts", []) or []) + (analysis.get("chart_specs", []) or [])
    )
    for artifact in analysis.get("analysis_artifacts", []) or analysis.get("chart_specs", []) or []:
        if isinstance(artifact, dict):
            if compact_whitespace(artifact.get("chart_type")).lower() == "decision_tree":
                visual = VisualSpec.from_any({"type": "structured_chart", **artifact})
                if visual:
                    headline = _decision_tree_visual_headline(visual)
                    data = visual.data if isinstance(visual.data, dict) else {}
                    note = first_nonempty(data.get("performance_note"), decision_tree_performance_note(data))
                    findings.extend(item for item in (headline, note) if compact_whitespace(item))
                continue
            for key in ("finding", "takeaway", "title"):
                text = compact_whitespace(artifact.get(key))
                if text:
                    findings.append(text)
                    break
    for item in analysis.get("business_findings", []) or []:
        text = compact_whitespace(item)
        if tree_present and "tree" in text.lower():
            continue
        if text:
            findings.append(text)
    summary = analysis.get("analysis_summary", {}) or {}
    if isinstance(summary, dict):
        for key, value in summary.items():
            if isinstance(value, (dict, list)):
                continue
            findings.append(f"{str(key).replace('_', ' ').title()}: {compact_whitespace(value)}")
    captions = analysis.get("figure_captions", {}) or {}
    if isinstance(captions, dict):
        findings.extend(compact_whitespace(value) for value in captions.values() if compact_whitespace(value))
    if not findings:
        findings.append("The analysis output did not include structured findings; use available summaries as directional evidence.")
    return refine_bullets(findings, max_items=8, max_chars=140)


def _summary_metrics(workflow_state: dict[str, Any]) -> list[dict[str, str]]:
    metrics: list[dict[str, str]] = []
    summary = workflow_state.get("analysis_results", {}).get("analysis_summary", {}) or {}
    if isinstance(summary, dict):
        for key, value in summary.items():
            if isinstance(value, (int, float)) and not isinstance(value, bool):
                metrics.append({"label": str(key).replace("_", " ").title(), "value": f"{value:g}"})
            elif isinstance(value, str) and any(char.isdigit() for char in value):
                metrics.append({"label": str(key).replace("_", " ").title(), "value": shorten(value, 26)})
            if len(metrics) >= 4:
                break
    return metrics


def _choose_template(existing: SlideSpec | None, visual: VisualSpec | None, fallback_template: str) -> str:
    if visual and visual.type == "structured_chart" and visual.recommended_template in TEMPLATE_REGISTRY:
        return visual.recommended_template or fallback_template
    if existing and existing.template:
        return existing.template
    return fallback_template


def _template_for_visual(visual: VisualSpec | None, offset: int) -> str:
    if visual and visual.type == "structured_chart":
        return visual.recommended_template if visual.recommended_template in TEMPLATE_REGISTRY else _template_for_chart_type(visual.chart_type)
    if visual and visual.type in {"code_figure", "legacy_image_fallback"}:
        return "full_width_chart_takeaway"
    return ANALYSIS_TEMPLATE_SEQUENCE[offset % len(ANALYSIS_TEMPLATE_SEQUENCE)]


def _template_for_chart_type(chart_type: str) -> str:
    normalized = compact_whitespace(chart_type).lower()
    return {
        "small_multiples_bar": "small_multiples_with_takeaway",
        "bar": "single_bar_chart_with_insight",
        "column": "single_bar_chart_with_insight",
        "horizontal_bar": "horizontal_bar_ranking",
        "line": "comparison_chart_with_interpretation",
        "scatter": "comparison_chart_with_interpretation",
        "distribution": "distribution_with_callout",
        "metric_cards": "metric_cards_with_chart",
        "decision_tree": "full_width_chart_takeaway",
    }.get(normalized, "comparison_chart_with_interpretation")


def _analysis_limitations(summary: Any) -> list[str]:
    if not isinstance(summary, dict):
        return []
    limitations: list[str] = []
    for key, value in summary.items():
        lowered = str(key).lower()
        if any(token in lowered for token in ("limitation", "caution", "assumption", "missing", "quality", "note")):
            text = compact_whitespace(value)
            if text:
                limitations.append(text)
    return limitations


def _headline_has_unsupported_ratio(headline: str, evidence_text: str) -> bool:
    return bool(
        re.search(r"\b\d+(?:\.\d+)?x\b", compact_whitespace(headline).lower())
        and "%" in compact_whitespace(evidence_text)
        and not re.search(r"\b\d+(?:\.\d+)?x\b", compact_whitespace(evidence_text).lower())
    )
